import { expect, test } from "./adult-fixture";
import { expectNoHorizontalOverflow } from "./layout";
import { mockVocabularyLearning } from "./vocabulary-learning-mock";

test("known recall hides target, persists sequential hints, composes shuffled chunks and polls feedback", async ({ page }, info) => {
  const errors: string[] = []; page.on("pageerror", error => errors.push(error.message));
  page.on("console", message => { if (["error", "warning"].includes(message.type()) && !/Failed to load resource.*503/.test(message.text())) errors.push(message.text()); });
  const state = await mockVocabularyLearning(page, { status: "QUEUED" });
  await page.goto("/vocabulary-practice/vp1");
  await expect(page).toHaveURL(/\/vocabulary-practice\/vp1$/);
  await expect(page).toHaveTitle(/文法/);
  await expect(page.getByRole("heading", { name: "词汇造句练习" })).toBeVisible();
  await expect(page.getByRole("button", { name: "查看词义提示" })).toBeVisible();
  await expect(page.getByText(/予定|よてい/)).toHaveCount(0);
  await expectNoHorizontalOverflow(page);
  await page.screenshot({ path: `/tmp/vocabulary-e-known-${info.project.name}.png`, fullPage: true });
  state.failHintOnce = true;
  await page.getByRole("button", { name: "查看词义提示" }).click();
  await expect(page.getByRole("main").getByRole("alert")).toContainText("提示暂不可用");
  await expect(page.getByText(/予定|よてい/)).toHaveCount(0);
  await page.getByRole("button", { name: "查看词义提示" }).click();
  await expect(page.getByText("词义提示：计划；预定")).toBeVisible();
  await expect(page.getByText(/予定|よてい/)).toHaveCount(0);
  await page.reload();
  await expect(page.getByText("词义提示：计划；预定")).toBeVisible();
  await page.getByRole("button", { name: "查看读音提示" }).click();
  await expect(page.getByText("读音提示：よてい")).toBeVisible();
  await expect(page.getByText("目标词：予定")).toHaveCount(0);
  await page.getByRole("button", { name: "查看目标词", exact: true }).click();
  await expect(page.getByText("目标词：予定")).toBeVisible();
  await page.getByRole("button", { name: "查看打乱词块" }).click();
  const chunks = page.getByRole("group", { name: "可选词块" });
  await chunks.getByRole("button", { name: "明日の", exact: true }).click();
  await chunks.getByRole("button", { name: "予定を", exact: true }).click();
  await chunks.getByRole("button", { name: "確認しておきます。", exact: true }).click();
  await page.getByRole("button", { name: "填入造句框" }).click();
  await expect(page.getByLabel("日语句子")).toHaveValue("明日の予定を確認しておきます。");
  await expectNoHorizontalOverflow(page);
  await page.screenshot({ path: `/tmp/vocabulary-e-chunks-${info.project.name}.png`, fullPage: true });
  state.failAnswerOnce = true;
  await page.getByRole("button", { name: "提交句子" }).click();
  await expect(page.getByRole("button", { name: "重试提交原句" })).toBeEnabled();
  await expect(page.getByLabel("日语句子")).toBeDisabled();
  await page.getByRole("button", { name: "重试提交原句" }).click();
  await expect(page.getByText(/句子已保存，正在批改/)).toBeVisible();
  await page.reload();
  await expect(page.getByText("词汇反馈 · 辅助练习")).toBeVisible({ timeout: 15000 });
  expect(state.answers).toHaveLength(2);
  expect(state.answers[1]).toEqual(state.answers[0]);
  expect(state.answers[0].requestKey).toMatch(/^[\da-f]{8}-[\da-f]{4}-4[\da-f]{3}-[89ab][\da-f]{3}-[\da-f]{12}$/i);
  expect(Object.keys(state.answers[0]).sort()).toEqual(["requestKey", "sentence"]);
  expect(state.hintBodies.every(body => JSON.stringify(body) === "{}")).toBe(true);
  await expect(page.getByText("未验证", { exact: true })).toBeVisible();
  await expect(page.getByText("下次复习：2026/9/15")).toBeVisible();
  await page.screenshot({ path: `/tmp/vocabulary-e-feedback-${info.project.name}.png`, fullPage: true });
  await expectNoHorizontalOverflow(page); expect(errors).toEqual([]);
});

test("unknown preview, bounded job retry, and detailed paginated history", async ({ page }) => {
  const state = await mockVocabularyLearning(page, { unknownAtStart: true, status: "FAILED", errorCode: "GENERATION_FAILED", learningPreview: {
    word: "予定", reading: "よてい", chineseGloss: "计划；预定", exampleSentence: "予定があります。", exampleFurigana: "予定[よてい]があります。", exampleTranslationZh: "有安排。",
  } });
  await page.goto("/vocabulary-practice/vp1");
  await expect(page.getByText("先认识这个词")).toBeVisible();
  await expect(page.getByText("计划；预定", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "重试生成" }).click();
  await expect(page.getByLabel("日语句子")).toBeEnabled();
  await page.getByLabel("日语句子").fill("予定があります。");
  await page.getByRole("button", { name: "提交句子" }).click();
  await expect(page.getByText("词汇反馈 · 辅助练习")).toBeVisible({ timeout: 15000 });
  state.practice.result = { ...state.practice.result!, outcome: "UNVERIFIED", usedTarget: false, targetCorrect: null, meaningCorrect: null, explanationZh: "另一种表达也自然，但没有使用目标词。", corrections: [{ text: "あります", replacement: "ありました", reason: "这里说的是过去的安排。" }] };
  await page.getByRole("link", { name: "查看此释义历史" }).click();
  await page.locator("summary").first().click();
  await expect(page.getByText(/这句话没有提供目标词的使用证据，不代表句子错误/)).toBeVisible();
  await expect(page.getByText("这里说的是过去的安排。")).toBeVisible();
  await page.getByRole("button", { name: "加载更多历史" }).click();
  await expect(page.locator("summary")).toHaveCount(2);
  await expect(page.getByRole("button", { name: "加载更多历史" })).toHaveCount(0);
  await expectNoHorizontalOverflow(page);
});

test("per-sense controls preserve remembered + practice, pause/resume/stop and list filters", async ({ page }, info) => {
  const state = await mockVocabularyLearning(page);
  await page.goto("/library");
  const cards = page.getByLabel("词汇卡片列表").locator('[data-slot="card"]');
  const first = cards.nth(0), second = cards.nth(1);
  await first.getByRole("button", { name: "根本不会", exact: true }).click();
  await expect(first.getByRole("button", { name: "根本不会", exact: true })).toHaveAttribute("aria-pressed", "true");
  await expect(first).toContainText("词义学习中");
  await expect(second.getByRole("button", { name: "根本不会", exact: true })).toHaveAttribute("aria-pressed", "false");
  await first.getByRole("button", { name: "认识但想练熟", exact: true }).click();
  await first.getByRole("button", { name: "已记住", exact: true }).click();
  await expect(first.getByRole("button", { name: "认识但想练熟", exact: true })).toHaveAttribute("aria-pressed", "true");
  await expect(first.getByRole("button", { name: "已记住", exact: true })).toHaveAttribute("aria-pressed", "true");
  await first.getByRole("button", { name: "暂停练习", exact: true }).click();
  await expect(first.getByRole("button", { name: "练习此释义" })).toBeDisabled();
  await first.getByRole("button", { name: "恢复练习", exact: true }).click();
  await expect(first.getByRole("button", { name: "练习此释义" })).toBeEnabled();
  await first.getByRole("button", { name: "停止练习", exact: true }).click();
  await expect(first.getByRole("button", { name: "已记住", exact: true })).toHaveAttribute("aria-pressed", "true");
  expect(state.actions).toEqual(["v1:UNKNOWN", "v1:PRACTICE", "v1:REMEMBERED", "v1:PAUSE", "v1:RESUME", "v1:STOP_PRACTICE"]);
  await page.getByLabel("内容类型").selectOption("learning");
  await page.getByRole("group", { name: "词汇学习清单", exact: true }).getByRole("button", { name: "根本不会" }).click();
  await page.getByLabel("学习词汇参考级别").selectOption("N1");
  await expect.poll(() => state.queries.at(-1)).toContain("list=UNKNOWN");
  const grid = page.getByLabel("学习词汇卡片列表");
  await expect(grid.getByRole("heading")).toHaveCount(3);
  expect(await grid.evaluate(el => getComputedStyle(el).gridTemplateColumns.split(" ").length)).toBe(info.project.name === "desktop" ? 3 : 1);
  await page.screenshot({ path: `/tmp/vocabulary-e-list-${info.project.name}.png`, fullPage: true });
  await expectNoHorizontalOverflow(page);
  await page.getByLabel("搜索学习词汇").fill("无结果");
  await page.getByRole("button", { name: "搜索", exact: true }).click();
  await expect(page.getByText("这个清单暂时没有词汇")).toBeVisible();
});

test("today works with paused grammar plan; grammar start sends context without a random word", async ({ page }) => {
  const state = await mockVocabularyLearning(page);
  await page.goto("/today");
  await expect(page.getByRole("region", { name: "今日词汇" })).toContainText("待复习 2 · 今日已完成 1");
  await page.getByRole("button", { name: "开始词汇练习" }).click();
  await expect(page).toHaveURL(/\/vocabulary-practice\/vp1$/);
  expect(state.starts[0]).toEqual({});
  await page.goto("/study/s1");
  state.noDue = true;
  await page.getByRole("button", { name: "练习到期词汇" }).click();
  await expect(page.getByRole("main").getByRole("alert")).toContainText("当前没有到期词汇");
  state.noDue = false;
  await page.getByRole("button", { name: "练习到期词汇" }).click();
  await expect(page).toHaveURL(/\/vocabulary-practice\/vp1$/);
  expect(state.starts.at(-1)).toEqual({ grammarId: "g1", studySessionId: "s1" });
});


test("stale markings and retry limit offer localized list recovery without error codes", async ({ page }) => {
  const state = await mockVocabularyLearning(page, { status: "FAILED", errorCode: "AI_FAILED", answer: "予定があります。" });
  state.retryLimit = true;
  await page.goto("/vocabulary-practice/vp1");
  await expect(page.getByText("AI_FAILED", { exact: false })).toHaveCount(0);
  await expect(page.getByLabel("日语句子")).toHaveValue("予定があります。");
  await page.getByRole("button", { name: "重试批改" }).click();
  await expect(page.getByText("这次练习已达到重试次数上限，请返回清单稍后重新开始。")).toBeVisible();
  await expect(page.getByRole("button", { name: "重试批改" })).toHaveCount(0);
  await expect(page.getByText(/RETRY_LIMIT|retry limit reached/)).toHaveCount(0);
  state.practice.errorCode = "LEARNING_CHANGED";
  await page.reload();
  await expect(page.getByText("词汇标记已更新，请从清单重新开始练习")).toBeVisible();
  await expect(page.getByRole("button", { name: "重试批改" })).toHaveCount(0);
  await expect(page.getByText("LEARNING_CHANGED", { exact: false })).toHaveCount(0);
  await page.getByRole("link", { name: "返回词汇学习清单" }).click();
  await expect(page).toHaveURL(/\/vocabulary-learning$/);
});
